Create navbar atomation
coni-code/web-conicode pull request #87
Opened 2024-02-10 13:15 UTC by MichalWegielski

### GOAL

Navbar automation is ready.

### PROOF OF IMPLEMENTATION 
![prooff](https://github.com/coni-code/web-conicode/assets/63373189/5084b46f-5fef-4419-9083-a6125118c981)

### TRELLO 

https://trello.com/c/5LvQ6d8l/560-navbar-automation

2024-02-10 13:50 UTC, MichalWegielski commented
There is strange situation where Js code cant pass eslint test instead of I repair all errors. It looks like code automaticly add blank space before and after "{" brackets on github platform.

2024-02-10 16:05 UTC, KiviGibson commented on assets/js/admin/topbar.js
Check errors in test before requesting to merge. Use quality command. You can get the command after you source the .profile file.

2024-02-10 16:05 UTC, KiviGibson commented on assets/js/website/navbar.js
same as above

2024-02-10 16:07 UTC, KiviGibson requested changes
Use quality command to check for errors in your code before merging.

2024-02-12 16:04 UTC, KiviGibson approved these changes

2024-02-12 16:31 UTC, merged