Update user table
coni-code/web-conicode pull request #89
Opened 2024-02-13 16:51 UTC by JozefPotaczek

### Goal
Add new fields in User table for social links and position. Adjust User panel with new fields.
### Proof of implem
![Screenshot from 2024-02-13 17-38-09](https://github.com/coni-code/web-conicode/assets/129151963/504268dc-f333-4abe-a826-c46cd35dc485)
entation
### Trello
https://trello.com/c/9ZVcLjHs/564-update-user-panel
https://trello.com/c/DcoZbzjM/546-update-user-database-schema

2024-02-14 06:20 UTC, bartek3xe requested changes

2024-02-14 06:20 UTC, bartek3xe commented on migrations/Version20240213121537.php
> +        // this down() migration is auto-generated, please modify it to your needs
Get rid of comments and merge migrations into one

2024-02-14 06:20 UTC, bartek3xe commented on templates/admin/user/_form.html.twig
> +        {% if is_admin(user) == true %}
{% if is_admin(user) %}

2024-02-14 06:20 UTC, bartek3xe commented on translations/messages+intl-icu.pl.yaml
> +
Remove unnecessary blank line

2024-02-18 20:27 UTC, KiviGibson approved these changes

2024-02-19 16:56 UTC, bartek3xe approved these changes

2024-02-19 16:57 UTC, merged